name: authorization_repository
description: Authorization manage.
publish_to: none


environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cache:
    path: ..\cache
  equatable: ^2.0.0
  google_sign_in: ^6.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_animated_button: ^2.0.3
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0

dev_dependencies:
  firebase_auth_platform_interface: ^7.4.7
  firebase_core_platform_interface: ^5.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8